-- File: task_4.sql
USE ${1};

SELECT
  COLUMN_NAME,
  COLUMN_TYPE,
  IS_NULLABLE,
  COLUMN_DEFAULT,
  COLUMN_KEY,
  EXTRA
FROM
  INFORMATION_SCHEMA.COLUMNS
WHERE
  TABLE_NAME = 'books'
  AND TABLE_SCHEMA = 'alx_book_store';
